# Generated by Django 2.1.5 on 2019-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
