# Generated by Django 2.1.5 on 2019-12-09 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentabook', '0006_auto_20191209_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='author',
            field=models.CharField(default='N/A', help_text='Enter book author', max_length=255),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='condition',
            field=models.CharField(choices=[('1', 'Like New'), ('2', 'Good'), ('3', 'Fair')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='rentabook.Genre'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='price',
            field=models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50)], default=10),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='title',
            field=models.CharField(default='N/A', help_text='Enter book title', max_length=255),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
