# Generated by Django 2.1.5 on 2019-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0007_auto_20191209_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='author',
            field=models.CharField(help_text='Enter book author', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='title',
            field=models.CharField(help_text='Enter book title', max_length=255),
        ),
    ]
