# Generated by Django 2.1.5 on 2019-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0009_auto_20191209_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
