# Generated by Django 2.1.5 on 2019-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0011_auto_20191209_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available'), ('m', 'Maintenance')], default='a', help_text='Book availability', max_length=1),
        ),
    ]
