# Generated by Django 2.1.5 on 2019-12-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0012_auto_20191218_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back', 'id']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
