# Generated by Django 3.0.3 on 2020-03-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0013_auto_20191224_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back', 'status']},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='background_color',
            field=models.CharField(blank=True, help_text='Enter background color', max_length=10),
        ),
    ]
