# Generated by Django 3.0.3 on 2020-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabook', '0014_auto_20200308_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='background_color',
            field=models.CharField(help_text='Enter background color', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book (max. 1000 characters)', max_length=1000),
        ),
    ]
